sudo netplan apply;
sudo apt-get update && apt-get upgrade;
sudo apt-get install -f -y openssh-server;
sudo apt-get install -f -y apache2;
sudo apt-get install -f -y php libapache2-mod-php php-mysql php-gd php-cli php-dev php-fpm php-dom php-xml php-mbstring php-opcapache php-readline php-curl php-intl php-common php-pear php-zip libargon2-0 libsodium23 libssl php-xmlrpc;
sudo apt-get install -f -y curl;
sudo apt-get install -f -y mysql-server;
sudo apt-get install -f -y phpmyadmin;
sudo apt-get install -f -y apache2-utils;
sudo apt-get install -f -y openssl;
sudo apt-get install -f -y vim;
sudo apt-get install -f -y nodejs;
sudo apt-get install -f -y npm;
sudo apt-get install -f -y build-essential libssl-dev;
sudo apt-get update; 
sudo apt-get upgrade;
sudo apt-get dist-upgrade 
sudo apt-get autoremove;
sudo apt-get install -f;
sudo apt-get autoremove;
sudo chmod -R 775 /var/www/;
sudo chmod -R 775 /var/www/html/;
sudo systemctl enable ssh;
sudo systemctl start ssh;
sudo service apache2 restart;
sudo systemctl restart apache2;